sudo: required

services:
  - docker

language: go

cache:
  directories:
    - .cache
    - $HOME/.build
    # cache the Go module cache
    - $HOME/gopath/pkg/mod
    # cache `go install`-ed binaries across stages. build.sh unsets GOPATH
    # so this is hitting the default go env of $HOME/go
    - $HOME/go/bin

stages:
  - test

jobs:
  include:
    - stage: test
      env:
        - CHANGE_MINIKUBE_NONE_USER=true
      os: linux
      dist: xenial
      before_script:
        # Download stable kubectl
        - curl -s -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
        # Download latest minikube
        - curl -s -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/
        # Start up minikube
        - sudo minikube start --vm-driver=none --extra-config=apiserver.service-account-signing-key-file=/var/lib/minikube/certs/sa.key --extra-config=apiserver.service-account-key-file=/var/lib/minikube/certs/sa.pub --extra-config=apiserver.service-account-issuer=api --extra-config=apiserver.service-account-api-audiences=api,spire-server --extra-config=apiserver.authorization-mode=RBAC

        # Make sure kubectl configuration is up to date
        - sudo chown -R $USER.$USER ~/.kube
        - sudo chown -R $USER.$USER ~/.minikube
        - minikube update-context

        # Wait for stuff to become ready
        - JSONPATH='{range .items[*]}{@.metadata.name}:{range @.status.conditions[*]}{@.type}={@.status};{end}{end}'; until kubectl get nodes -o jsonpath="$JSONPATH" 2>&1 | grep -q "Ready=True"; do sleep 1; done

         # Get SPIRE master (we need it to build k8s-test tool)
        - git clone https://github.com/spiffe/spire.git

      script:
        # Run systems tests
        - examples/k8s/test-all.sh
